import Link from "next/link";
import { categoryConfig } from "@/data/categories";
import { FeedbackForm } from "@/components/FeedbackForm";

export function ProjectSections() {
  return <>
    <section id="entdecken" className="discover-section shell" aria-labelledby="discover-title"><div className="section-intro"><div><p className="eyebrow">Deine Themenwelten</p><h2 id="discover-title">Was macht einen Ort <span>kinderfreundlich?</span></h2></div><p>Kinderfreundlichkeit hat viele Seiten. Entdecke die Themen, die unsere Roadmap verbinden.</p></div><div className="category-cards">{categoryConfig.slice(0, 5).map((category) => <div className="category-card" key={category.key} style={{ "--card-color": category.color, "--card-soft": category.softColor } as React.CSSProperties}><span className="category-card__icon">{category.icon}</span><h3>{category.label}</h3><p>{category.description}</p><Link href={`/#karte`} className="card-link">Orte ansehen <span aria-hidden="true">→</span></Link></div>)}</div></section>
    <section id="mitmachen" className="participation-section shell" aria-labelledby="participation-title"><div className="participation-intro"><p className="eyebrow">Deine Stimme zählt</p><h2 id="participation-title">Was fehlt dir noch in <span>Eltville?</span></h2><p>Du kennst einen Ort, der auf der Roadmap fehlt? Oder du hast eine Idee, wie ein Ort noch besser werden kann? Erzähl es uns.</p><div className="participation-points"><span>✦ kurz & einfach</span><span>✦ ohne Pflichtangaben</span><span>✦ wird geprüft</span></div></div><div className="form-card"><FeedbackForm /></div></section>
    <section id="projekt" className="about-section shell" aria-labelledby="about-title"><div className="about-art"><img src="/assets/practice-guide-cover.png" alt="Projektmotiv mit Kindern am Rhein" loading="lazy" decoding="async" /></div><div className="about-copy"><p className="eyebrow">Über das Projekt</p><h2 id="about-title">Gemeinsam. <span>heute für morgen.</span></h2><p>Eltville ist seit 2019 Teil des Programms Kinderfreundliche Kommunen. Die Roadmap macht sichtbar, was schon da ist – und lädt dazu ein, gemeinsam weiterzudenken.</p><div className="about-facts"><div><strong>01</strong><span>Kinder haben Platz zum Spielen und Bewegen.</span></div><div><strong>02</strong><span>Kinder können mitreden und mitgestalten.</span></div><div><strong>03</strong><span>Eltville ist grün, gesund und lebenswert.</span></div></div><Link className="button button--blue" href="/#mitmachen">Mitmachen <span aria-hidden="true">→</span></Link></div></section>
  </>;
}
